name: misuzu-bot
version: 0.0.0
description: ''
type: module
scripts:
  build: node scripts/build.ts
  test: tsc
keywords: []
author: ''
license: AGPL-3.0-or-later
packageManager: pnpm@10.18.0
devDependencies:
  esbuild: ^0.25.11
  typescript: ^5.9.3
dependencies:
  '@octokit/app': ^16.1.1
